import React from 'react';
import type { ProcessStage, Role } from './types';
import {
    TruckIcon, 
    ScaleIcon, 
    BeakerIcon, 
    ArchiveBoxIcon, 
    CogIcon, 
    CubeIcon, 
    PaperAirplaneIcon, 
    ShieldCheckIcon,
    SparklesIcon,
    DocumentTextIcon 
} from './components/Icons';

export const PROCESSING_STAGE_COLUMNS = [
    'Pre Cleaning',
    'Oiling',
    'Dry',
    'Water',
    'Processed'
];

export const PROCESS_STAGES: ProcessStage[] = [
    {
        id: 'arrival',
        name: 'Gate Entry Stage',
        responsibleRole: 'Gate Entry Operator',
        erpModule: 'Arrival_Form',
        dependentOn: 'Supplier Schedule',
        output: 'Arrival Slip',
        description: 'Security logs incoming and outgoing vehicle details, including driver and broker information.',
        color: {
            bg: 'bg-gray-100',
            text: 'text-gray-800',
            border: 'border-gray-300'
        },
        icon: <TruckIcon />,
        formFields: [
            { name: 'gate_mode', label: 'Entry Type', type: 'text' },
            { name: 'timestamp', label: 'Timestamp', type: 'text' },
            { name: 'serial_number', label: 'Serial Number', type: 'text' },
            { name: 'vehicle_number', label: 'Vehicle Number', type: 'text' },
            { name: 'driver_name', label: 'Driver Name', type: 'text' },
            { name: 'phone_number', label: 'Driver Phone', type: 'tel' },
            { name: 'note', label: 'Note', type: 'textarea' },
            { name: 'from_broker', label: 'From Broker', type: 'text' },
            { name: 'to_location', label: 'To', type: 'text' },
            { name: 'quantity', label: 'Quantity', type: 'number' },
            { name: 'from_location', label: 'From', type: 'text' },
            { name: 'broker_name', label: 'Broker Name', type: 'text' },
            { name: 'broker_phone', label: 'Broker Phone', type: 'tel' },
        ],
    },
    {
        id: 'weighing',
        name: 'Weighing Stage',
        responsibleRole: 'Weighing Operator',
        erpModule: 'Weighing_Module',
        dependentOn: 'Vehicle Entry',
        output: 'Net Weight Slip',
        description: 'Gross and Out weights are recorded to determine the net weight of the materials.',
        color: {
            bg: 'bg-pink-100',
            text: 'text-pink-800',
            border: 'border-pink-300'
        },
        icon: <ScaleIcon />,
        formFields: [
            { name: 'weighing_heading', label: 'Weighing Machine', type: 'heading' },
            { name: 'vehicle_number', label: 'Vehicle No', type: 'text', placeholder: 'e.g., AP00XX0000' },
            { name: 'ticket_no', label: 'Ticket No', type: 'text', placeholder: 'Generated by device' },
            { name: 'note', label: 'Note', type: 'textarea', placeholder: 'Add any relevant notes' },
            { name: 'gross_weight', label: 'In weight', type: 'number', placeholder: 'e.g., 500.5 Quintal' },
            { name: 'tare_weight', label: 'Out weight', type: 'number', placeholder: 'e.g., 255.0 Quintal' },
            { name: 'sample_collector', label: 'Sample Collector', type: 'text', placeholder: 'e.g., John Doe' },
        ],
    },
    {
        id: 'quality-check',
        name: 'Initial Quality Check',
        responsibleRole: 'Quality Operator',
        erpModule: 'Quality_Module',
        dependentOn: 'Weighing',
        output: 'Quality Report',
        description: 'A sample is drawn for quality inspection. The batch is either approved for the next stage or rejected.',
        color: { 
            bg: 'bg-purple-100',
            text: 'text-purple-800',
            border: 'border-purple-300'
        },
        icon: <BeakerIcon />,
        formFields: [
            { name: 'quality_check_heading', label: 'Quality Check', type: 'heading' },
            { name: 'vehicle_number', label: 'Vehicle Number', type: 'text', placeholder: 'e.g., AP00XX0000' },
            { name: 'transaction_id', label: 'Transaction ID', type: 'text', placeholder: 'Auto-generated or manual' },
            { name: 'note', label: 'Note', type: 'textarea', placeholder: 'Add any notes here' },
            { name: 'size_analysis_7', label: '7 No', type: 'number', placeholder: '0' },
            { name: 'size_analysis_5', label: '5 No', type: 'number', placeholder: '0' },
            { name: 'size_analysis_4', label: '4 No', type: 'number', placeholder: '0' },
            { name: 'small_mud_percent', label: 'SM %', type: 'number', placeholder: '0' },
            { name: 'big_mud_stones_percent', label: 'LM %', type: 'number', placeholder: '0' },
            { name: 'damage_1', label: 'Damage 1', type: 'number', placeholder: '0' },
            { name: 'physical_damage_2', label: 'Damage 2', type: 'number', placeholder: '0' },
            { name: 'moisture_content_percent', label: 'Moisture %', type: 'number', placeholder: '0' },
            { name: 'upload_report', label: 'Upload Report', type: 'file' },
        ],
    },
    {
        id: 'bin_operation',
        name: 'Bin Operation',
        responsibleRole: 'Bin Operator',
        erpModule: 'Bin_Management',
        dependentOn: 'Initial Quality Check',
        output: 'Bin Assignment Log',
        description: 'Assigns quality-approved materials to specific storage bins for resting and processing.',
        color: {
            bg: 'bg-orange-100',
            text: 'text-orange-800',
            border: 'border-orange-300'
        },
        icon: <ArchiveBoxIcon />,
        formFields: [
            { name: 'bin_operation_heading', label: 'Bin Operation', type: 'heading' },
            { name: 'vehicle_number', label: 'Vehicle Number', type: 'dropdown' },
            { name: 'bin_status', label: 'Bin Status', type: 'dropdown', options: ['Fill', 'Discharge', 'Maintenance'] },
            { name: 'rm1', label: 'RM1', type: 'text', placeholder: 'Enter value' },
            { name: 'rm2', label: 'RM2', type: 'text', placeholder: 'Enter value' },
            { name: 'rm3', label: 'RM3', type: 'text', placeholder: 'Enter value' },
            { name: 'bins_heading', label: 'Bins', type: 'heading' },
            { name: 'ob_quantity', label: 'OB Quantity', type: 'number', placeholder: '0' },
            { name: 'cb_quantity', label: 'CB Quantity', type: 'number', placeholder: '0' },
            { name: 'wb_quantity', label: 'WB Quantity', type: 'number', placeholder: '0' },
            { name: 'pb_quantity', label: 'PB Quantity', type: 'number', placeholder: '0' },
            { name: 'sr_in_quantity', label: 'SR IN Quantity', type: 'number', placeholder: '0' },
            { name: 'hub_quantity', label: 'HUB Quantity', type: 'number', placeholder: '0' },
        ],
    },
    {
        id: 'cleaning',
        name: 'Cleaning Stage',
        responsibleRole: 'Cleaning Operator',
        erpModule: 'Cleaning_Module',
        dependentOn: 'Raw Dal Arrival',
        output: 'Cleaned Batch Log',
        description: 'Removal of dust, stones, and Other impurities from the raw dal.',
        color: {
            bg: 'bg-teal-100',
            text: 'text-teal-800',
            border: 'border-teal-300'
        },
        icon: <SparklesIcon />,
        formFields: [
            { name: 'batch_id', label: 'Batch ID', type: 'text', placeholder: 'e.g., CLN-20251027-001' },
            { name: 'machine_no', label: 'Machine No', type: 'text', placeholder: 'e.g., MC-05' },
        ],
    },
    {
        id: 'storage',
        name: 'Storage Stage',
        responsibleRole: 'Store Operator',
        erpModule: 'Storage_Module',
        dependentOn: 'Quality Check',
        output: 'Stored Batch Record',
        description: 'The approved batch is assigned to storage bins for a 72-hour rest period.',
        color: {
            bg: 'bg-yellow-100',
            text: 'text-yellow-800',
            border: 'border-yellow-300'
        },
        icon: <ArchiveBoxIcon />,
        formFields: [
            { name: 'storage_heading', label: 'Storage Details', type: 'heading' },
            { name: 'entered_vehicle', label: 'Entered Vehicle', type: 'text', placeholder: 'e.g., AP00XX0000' },
            { name: 'quantity', label: 'Quantity (in Quintal)', type: 'number', placeholder: 'e.g., 250' },
            { name: 'material_content', label: 'Material Content', type: 'dropdown', options: ['M1', 'M2', 'M3', 'M4', 'M5'] },
            { name: 'jute_bags_quantity', label: 'Jute Bags Quantity', type: 'number', placeholder: 'e.g., 500' },
            { name: 'plastic_bags_quantity', label: 'Plastic Bags Quantity', type: 'number', placeholder: 'e.g., 0' },
            { name: 'location_main', label: 'Location (Area)', type: 'dropdown', options: ['Kallam', 'Baddi', 'Godown'] },
            { name: 'location_sub', label: 'Location (Unit)', type: 'dropdown' },
        ],
    },
    {
        id: 'processing',
        name: 'Processing Stage',
        responsibleRole: 'Plant Operator',
        erpModule: 'Processing_Module',
        dependentOn: 'Storage',
        output: 'Processed Dal Output',
        description: 'Milling or splitting process, including de-husking, sorting, and grading.',
        color: {
            bg: 'bg-fuchsia-100',
            text: 'text-fuchsia-800',
            border: 'border-fuchsia-300'
        },
        icon: <CogIcon />,
        formFields: [
            { name: 'processing_heading', label: 'Processing Details', type: 'heading' },
            { name: 'vehicle_number', label: 'Vehicle Number', type: 'dropdown' },
            { name: 'brand', label: 'Brand', type: 'dropdown', options: ['Double horse', 'Maharani'] },
            { name: 'stage_table_heading', label: 'Stage Table', type: 'heading' }
        ],
    },
    {
        id: 'quality_check_2',
        name: 'Final Quality Check',
        responsibleRole: 'Quality Operator',
        erpModule: 'Quality_Module',
        dependentOn: 'Processing',
        output: 'Final QC Report',
        description: 'Ensures compliance of the processed dal before it moves to packing.',
        color: {
            bg: 'bg-red-100',
            text: 'text-red-800',
            border: 'border-red-300'
        },
        icon: <ShieldCheckIcon />,
        formFields: [
            { name: 'final_moisture_percent', label: 'Final Moisture (%)', type: 'number', placeholder: 'e.g., 11.0' },
            { name: 'split_percentage', label: 'Split Percentage', type: 'number', placeholder: 'e.g., 99.8' },
            { name: 'final_remarks', label: 'Final Remarks', type: 'textarea', placeholder: 'e.g., Ready for packing' },
        ],
    },
    {
        id: 'packing',
        name: 'Packing Stage',
        responsibleRole: 'Packaging Operator',
        erpModule: 'Packing_Module',
        dependentOn: 'Final Quality Re-Check',
        output: 'Packed Goods Record',
        description: 'The finished product is packed into bags of various sizes (e.g., 25kg, 50kg).',
        color: {
            bg: 'bg-green-100',
            text: 'text-green-800',
            border: 'border-green-300'
        },
        icon: <CubeIcon />,
        formFields: [
            { name: 'packing_id', label: 'Packing ID', type: 'text', placeholder: 'e.g., PACK-001' },
            { name: 'bag_size_kg', label: 'Bag Size (ql)', type: 'dropdown', options: ['25', '50', '100'] },
            { name: 'no_of_bags', label: 'Number of Bags', type: 'number', placeholder: 'e.g., 200' },
        ],
    },
    {
        id: 'sales',
        name: 'Sales Stage',
        responsibleRole: 'Sales Operator',
        erpModule: 'Sales_Module',
        dependentOn: 'Packing',
        output: 'Sales Report',
        description: 'Upload daily sales export and review line-item details before dispatch.',
        color: {
            bg: 'bg-amber-100',
            text: 'text-amber-800',
            border: 'border-amber-300'
        },
        icon: <DocumentTextIcon />,
        formFields: [
            { name: 'sales_heading', label: 'Sales Details', type: 'heading' },
            { name: 'sales_timestamp', label: 'Timestamp', type: 'text' },
            { name: 'sales_upload', label: 'Upload Sales File', type: 'file' }
        ],
    },
    {
        id: 'dispatch',
        name: 'Dispatch Stage',
        responsibleRole: 'Dispatch Operator',
        erpModule: 'Dispatch_Module',
        dependentOn: 'Packing',
        output: 'Dispatch Note / Gate Pass',
        description: 'Packed goods are loaded onto vehicles for delivery to clients or distribution centers.',
        color: {
            bg: 'bg-sky-100',
            text: 'text-sky-800',
            border: 'border-sky-300'
        },
        icon: <PaperAirplaneIcon />,
        formFields: [
            { name: 'dispatch_details_heading', label: 'Dispatch Details', type: 'heading' },
            { name: 'vehicle_number', label: 'Vehicle Number', type: 'text', placeholder: 'e.g., TS09AB1234' },
            { name: 'destination', label: 'Destination', type: 'text', placeholder: 'e.g., Hyderabad' },
            { name: 'client_name', label: 'Client Name', type: 'text', placeholder: 'e.g., Global Exports Inc.' },
            { name: 'no_of_bags', label: 'No of Bags', type: 'number', placeholder: 'e.g., 200' },

            { name: 'item_list_heading', label: 'Item Details', type: 'heading' },
            { name: 'item_1_name', label: 'Item 1 Name', type: 'text', placeholder: 'e.g., Toor Dal' },
            { name: 'item_1_quantity', label: 'Item 1 Quantity (Qtl)', type: 'number', placeholder: '0' },
            { name: 'item_2_name', label: 'Item 2 Name', type: 'text', placeholder: 'e.g., Moong Dal' },
            { name: 'item_2_quantity', label: 'Item 2 Quantity (Qtl)', type: 'number', placeholder: '0' },
            { name: 'item_3_name', label: 'Item 3 Name', type: 'text' },
            { name: 'item_3_quantity', label: 'Item 3 Quantity (Qtl)', type: 'number' },
            { name: 'item_4_name', label: 'Item 4 Name', type: 'text' },
            { name: 'item_4_quantity', label: 'Item 4 Quantity (Qtl)', type: 'number' },
            { name: 'item_5_name', label: 'Item 5 Name', type: 'text' },
            { name: 'item_5_quantity', label: 'Item 5 Quantity (Qtl)', type: 'number' },
            { name: 'item_6_name', label: 'Item 6 Name', type: 'text' },
            { name: 'item_6_quantity', label: 'Item 6 Quantity (Qtl)', type: 'number' },

            { name: 'weight_heading', label: 'Weight Details', type: 'heading' },
            { name: 'gross_weight', label: 'In weight (Qtl)', type: 'number', placeholder: 'Weight of vehicle with goods' },
            { name: 'tare_weight', label: 'Out weight (Qtl)', type: 'number', placeholder: 'Weight of empty vehicle' },
            
            { name: 'note', label: 'Notes / Remarks', type: 'textarea' },
        ],
    }
];

export const ROLE_PERMISSIONS: Partial<Record<Role, string[]>> = {
    ADMIN: ['*'],
    MANAGER: ['*'],
    ASSISTANT_MANAGER: ['*'],
    GATE_ENTRY_OPERATOR: ['arrival'],
    WEIGHING_OPERATOR: ['weighing'],
    CLEANING_OPERATOR: ['cleaning'],
    QUALITY_OPERATOR: ['quality-check', 'quality_check_2'],
    BIN_OPERATOR: ['bin_operation'],
    STORE_MANAGER: ['storage'],
    PLANT_OPERATOR: ['processing'],
    PACKAGING_OPERATOR: ['packing'],
    SALES_OPERATOR: ['sales'],
    DISPATCH_OPERATOR: ['dispatch']
};